version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: vduck
    main: .
    binary: vduck
    env:
      - CGO_ENABLED=1
    flags:
      - -trimpath
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: darwin
        goarch: amd64
    overrides:
      - goos: linux
        goarch: arm64
        env:
          - CC=aarch64-linux-gnu-gcc
          - CXX=aarch64-linux-gnu-g++
      - goos: darwin
        goarch: arm64
        env:
          - CC=oa64-clang
          - CXX=oa64-clang++

archives:
  - id: default
    ids:
      - vduck
    formats: ['tar.gz']
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  footer: >-

    ---

    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).
