name: Publish Go Release

on:
  push:
    tags:
      - "*"

permissions:
  contents: read

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Release
        run: |
          docker run --rm --privileged \
            -v "$PWD":/go/src/vduck \
            -w /go/src/vduck \
            -e GITHUB_TOKEN \
            ghcr.io/goreleaser/goreleaser-cross:v1.26.3 \
            release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
